Final-year-project/about/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.about, name="about")
 ]

Final-year-project/eshopper/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/',include(('about.urls','about'),namespace='about')),
    path('',include('home.urls')),
    path('cart/',include('cart.urls',)),
    path('contact/',include('contact.urls')),
    path('faq/',include('faq.urls')),
    path('orders/',include('orders.urls')),
    # path('',include('about.urls')),
    
]
if settings.DEBUG:
            urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Final-year-project/faq/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('faque', view=views.faq,name='faq'),
 ]

Final-year-project/onlineshop/urls.py
from django.urls import re_path as url
from django.utils.translation import gettext_lazy as _

from . import views

urlpatterns = [
    url(
        regex=_(r'^product_list/$'),
        view=views.product_list,
        name='product_list'
    ),

    url(
        regex=r'^(?P<category_slug>[-\w]+)/$',
        view=views.product_list,
        name='product_list_by_category'
    ),

    url(
        regex=r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        view=views.product_detail,
        name='product_detail'),

]

Final-year-project/onlineshop/models.py
from django.db import models
from django.urls import reverse
from parler.models import TranslatableModel, TranslatedFields


class Category(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(max_length=200, db_index=True),
        slug=models.SlugField(max_length=200, db_index=True, unique=True)
    )

    class Meta:
        # ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('onlineshop:product_list_by_category', args=[self.slug])


class Product(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(max_length=200, db_index=True),
        slug=models.SlugField(max_length=200, db_index=True),
        description=models.TextField(blank=True)
    )
    category = models.ForeignKey(Category, related_name='products',on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('available',)
        # index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('onlineshop:product_detail', args=[self.id, self.slug])


# Model for Product Reviews


class Review(models.Model):
    product = models.ForeignKey(Product, related_name='reviews',on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Review by {} on {}'.format(self.name, self.product)

Final-year-project/onlineshop/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q

# Create your views here.
from django.shortcuts import get_object_or_404, render

from cart.forms import CartAddProductForm

from .forms import ReviewForm
from .models import Category, Product, Review
from .recommender import Recommender


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        language = request.LANGUAGE_CODE
        category = get_object_or_404(Category, translations__language_code=language,
                                     translations__slug=category_slug)
        products = products.filter(category=category)

    cart_product_form = CartAddProductForm()
    return render(request, 'onlineshop/product/product-list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products,
                   'cart_product_form': cart_product_form,
                   })


def product_detail(request, id, slug):
    language = request.LANGUAGE_CODE
    product = get_object_or_404(Product, id=id, translations__language_code=language,
                                translations__slug=slug, available=True)
    # List of active comments for this product.
    reviews = product.reviews.filter(active=True)

    if request.method == "POST":
        # A review form was posted.
        review_form = ReviewForm(request.POST)
        print(review_form)
        if review_form.is_valid():
            # Create Review object but do not save to database yet.
            new_review = review_form.save(commit=False)
            # Assign the current product to the review
            new_review.product = product
            # Save the review to the database
            new_review.save()
    else:
        review_form = ReviewForm()

    cart_product_form = CartAddProductForm()
    r = Recommender()
    recommended_products = r.suggest_products_for([product], 3)
    return render(request, 'onlineshop/product/product-detail.html', {'product': product,
                                                                      'reviews': reviews,
                                                                      'review_form': review_form,
                                                                      'cart_product_form': cart_product_form,
                                                                      'recommended_products': recommended_products})

Final-year-project/onlineshop/templates/onlineshop/base.html
{% load i18n %}

{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Favicons -->
    <link rel="shortcut icon" href="{% static 'img/favi.gif' %}">

    <!-- Title -->
    <title>{% trans "E-Shopper" %} | {% block title %}{% endblock %}</title>

    <!-- Bootstrap Files and Plugins -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="{% static 'css/price-range.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
	<link href="{% static 'css/main.css' %}" rel="stylesheet">
	<link href="{% static 'css/responsive.css' %}" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">

   <!-- Crisp Live Chat -->
   <script type="text/javascript"> window.$crisp=[];window.CRISP_WEBSITE_ID="38d6144c-67a0-4b31-8cfb-2ee97bf4c905";(function(){ d=document;s=d.createElement("script"); s.src="https://client.crisp.chat/l.js"; s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})(); </script>
</head>

<body>
   {% block header %}
<header id="header"><!--header-->
		<div class="header_top"><!--header_top-->
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<div class="contactinfo">
							<ul class="nav nav-pills">
								<li><a href="#"><i class="fa fa-phone"></i> +233 20 18 75 333</a></li>
								<li><a href="mailto:info@eshopper.com"><i class="fa fa-envelope"></i> info@eshopper.com</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="social-icons pull-right">
							<ul class="nav navbar-nav">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
								<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
								<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header_top-->

		<div class="header-middle"><!--header-middle-->
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						<div class="logo pull-left">
							<a href="{% url 'home' %}"><img src="{% static 'img/logo.png' %}" alt="" /></a>
						</div>
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
						<div class="btn-group pull-right">
							<div class="btn-group">
								<button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
									Choose Your Language
									<span class="caret"></span>
								</button>
								<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenuLink">
                                    {% for language in languages %}
									<li><a href="/{{ language.code }}/" {% if language.code == LANGUAGE_CODE %} class="dropdown-item"{% endif %}>{{ language.name }}</a>
                                    </li>
                                    {% endfor %}
								</ul>
							</div>
						</div>
					</div>
					<div class="col-sm-8">
						<div class="shop-menu pull-right">
							<ul class="nav navbar-nav">
								{% comment %} <li><a href="{% url 'profiles:profile_home' %}"><i class="fa fa-user"></i>{% trans "Account" %}</a></li>
								<li><a href="{% url 'orders:order_create' %}"><i class="fa fa-crosshairs"></i>{% trans "Checkout" %}</a></li>
								<li><a href="{% url "cart:cart_detail" %}">{{ total_items }}<i class="fa fa-shopping-cart"></i>{% trans "Cart" %}</a></li>
								<li><a href="{% url 'auth_login' %}"><i class="fa fa-lock"></i>{% trans "Login" %}</a></li> {% endcomment %}
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-middle-->

		<div class="header-bottom"><!--header-bottom-->
			<div class="container">
				<div class="row">
					<div class="col-sm-9">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
								<span class="sr-only">{% trans "Toggle navigation" %}</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
						<div class="mainmenu pull-left">
							<ul class="nav navbar-nav collapse navbar-collapse">
								<li><a href="{% url 'home' %}" class="active">{% trans "Home" %}</a></li>
                                {% comment %} <li><a href="{% url 'onlineshop:product_list' %}">{% trans "Shop" %}</a></li>
                                <li><a href="{% url 'about:about' %}">{% trans "About Us" %}</a></li>
								<li><a href="{% url 'contact:contact' %}">{% trans "Contact Us" %}</a></li> {% endcomment %}
							</ul>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="search_box pull-right" >
							{% comment %} <form method="GET" action="{% url 'watson:search' %}"> {% endcomment %}
                            <input type="text" name="q" value="{{request.GET.q}}" placeholder="{% trans "Search Products" %}"/>
                            </form>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-bottom-->
	</header><!--/header-->

   {% endblock %}



        {% block content %}
        {% endblock %}


     <br />
<br />


   {% block footer %}
	<footer id="footer"><!--Footer-->
		<div class="footer-top">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="companyinfo">
							<h2><span>{% trans "E" %}</span>{% trans "-Shopper" %}</h2>
							<p>{% trans "Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor" %}</p>
						</div>
					</div>
					<div class="col-sm-7">
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="{% static 'img/iframe1.png' %}" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>{% trans "Circle of Hands" %}</p>
								<h2>{% trans "24 DEC 2017" %}</h2>
							</div>
						</div>

						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="{% static 'img/iframe2.png' %}" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>{% trans "Circle of Hands" %}</p>
								<h2>{% trans "24 DEC 2017" %}</h2>
							</div>
						</div>

						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="{% static 'img/iframe3.png' %}" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>{% trans "Circle of Hands" %}</p>
								<h2>{% trans "24 DEC 2017" %}</h2>
							</div>
						</div>

						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="{% static 'img/iframe4.png' %}" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>{% trans "Circle of Hands" %}</p>
								<h2>{% trans "24 DEC 2017" %}</h2>
							</div>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="address">
							<img src="{% static 'img/map.png' %}" alt="" />
							<p>P.O.Box KS 10731, Kumasi - Ghana</p>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="footer-widget">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>{% trans "Service" %}</h2>
							<ul class="nav nav-pills nav-stacked">
								{% comment %} <li><a href="{% url 'contact:contact' %}">{% trans "Contact Us" %}</a></li> {% endcomment %}
								<li><a href="#">{% trans "Order Status" %}</a></li>

							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>{% trans "Support" %}</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">{% trans "Copyright" %}</a></li>
								{% comment %} <li><a href="{% url 'faq:faq' %}">{% trans "FAQ’s" %}</a></li> {% endcomment %}

							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>{% trans "Policies" %}</h2>
							<ul class="nav nav-pills nav-stacked">
								{% comment %} <li><a href="{% url 'privacy:privacy-policy' %}">{% trans "Privacy Policy" %}</a></li>
								<li><a href="{% url 'refund:refund-policy' %}">{% trans "Refund Policy" %}</a></li> {% endcomment %}
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>{% trans "About Shopper" %}</h2>
							<ul class="nav nav-pills nav-stacked">
								{% comment %} <li><a href="{% url 'about:about' %}">{% trans "About Us" %}</a></li> {% endcomment %}
								<li><a href="#">{% trans "Careers" %}</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3 col-sm-offset-1">
						<div class="single-widget">
							<h2>{% trans "About Shopper" %}</h2>
							<form enctype="multipart/form-data" method="post" action="/newsletter/e-shopper/subscribe/" class="searchform">
								{% csrf_token %}
								<input type="email" name="email_field" required="" id="id_email_field" placeholder="Your email address">
								<button id="id_submit" name="submit" value="Subscribe" class="btn btn-default" type="submit"><i class="fa fa-arrow-circle-o-right"></i></button>
								<p>{% trans "Get the most recent updates from" %} <br />{% trans "E-Shopper and be updated your self..."%}</p>
							</form>
						</div>
					</div>

				</div>
			</div>
		</div>

		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<p class="pull-left">Copyright © 2017 - 2018 E-Shopper Inc. All rights reserved.</p>
					<p class="pull-right">{% trans "Developed by" %} <span><a target="_blank" href="https://paawillysite.wordpress.com/">{% trans "Williano" %}</a></span></p>
				</div>
			</div>
		</div>

	</footer><!--/Footer-->

   {% endblock %}


    <script src="{% static 'js/jquery.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
	<script src="{% static 'js/price-range.js' %}"></script>
    <script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>